### ISSUE TITLE
WEST timezone sometimes incorrectly flagged

### ISSUE THREAD

**Issue by hunter-read** [hunter-read/lfg-notify-bot#1]
Occasionally the WEST timezone is flagged when the word west is used in the submission to refer to west coast or other words sentences with the work west in them. Need to add a way to verify if timezone or word in sentence.

**Comment by axelDenoual** [comment]
Would there be a problem with taking the re.IGNORECASE flag out for the _tz_regex pattern in src/service/timezone_parser.py ? This would make the pattern catch only uppercase timezone codes.

**Comment by hunter-read** [comment]
I have thought of that, but due to there being no guarantee that a submission will use uppercase timezones it is tricky. I have frequently seen posts use something like (Mondays pst) or [8-12pm Pst] or just PST. WEST timezone may have to be omitted.

**Comment by axelDenoual** [comment]
Fair point. Great project by the way !
